version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_dbms_default_database=neo4j
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.meta.*,apoc.convert.*
    networks:
      - rag-network

  rag_service:
    build: ./rag_service
    environment:
      - PYTHONPATH=/app
      - USER_AGENT=private-ai-rag-graph
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_password
      - KG_CHUNK_SIZE=300
      - KG_CHUNK_OVERLAP=50
      - KG_MAX_TOKENS=500
      - KG_ENABLE_VISUALIZATION=true
    volumes:
      - ./rag_service:/app
      - chroma_db_data:/app/chroma_db
      - embedding_cache:/app/embedding_cache
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      # - ollama_server_lite
      - ollama_server
      - neo4j
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
    networks:
      - rag-network

  kg_rag:
    build: ./knowledge_graph
    environment:
      - PYTHONPATH=/app
      - USER_AGENT=private-ai-rag-graph
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_password
      - KG_CHUNK_SIZE=300
      - KG_CHUNK_OVERLAP=50
      - KG_MAX_TOKENS=500
      - KG_ENABLE_VISUALIZATION=true
    volumes:
      - ./knowledge_graph:/app
      - chroma_db_data:/app/chroma_db
      - embedding_cache:/app/embedding_cache
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      # - ollama_server_lite
      - ollama_server
      - neo4j
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
    networks:
      - rag-network

  # ollama_server_lite:
  #   image: langgraph_example-ollama_server_lite:latest
  #   build: 
  #     context: ./ollama_server
  #   container_name: ollama_server_lite
  #   ports:
  #     - "11435:11434"
  #   volumes:
  #     - .:/app
  #     - ./ollama_data:/root/.ollama
  #     - ./ollama_models:/root/.ollama/models
  #   entrypoint: ["/bin/bash", "/app/ollama_server/entrypoint.sh"]
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.00'
  #         memory: 8G
  #   networks:
  #     - rag-network

  ollama_server:
    image: ollama_server:latest
    build: 
      context: ./ollama_server
    container_name: ollama_server
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_NO_ALIGNMENT_WARNING=1
    volumes:
      - .:/app
      - ./ollama_data_large:/root/.ollama
      - ./ollama_models_large:/root/.ollama/models
    entrypoint: ["/bin/bash", "/app/ollama_server/entrypoint.sh"]
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 8G
    networks:
      - rag-network

  streamlit_app:
    build: ./chat
    container_name: streamlit_app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      # - ollama_server_lite
      - ollama_server
      - rag_service
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G
    networks:
      - rag-network

volumes:
  # ollama_data:
  # ollama_models:
  ollama_data_large:
  ollama_models_large:
  chroma_db_data:
  embedding_cache:

networks:
  rag-network:
    driver: bridge
